### ISSUE TITLE
[Pharo-5.0] Could not resolve: BaselineOfFileTree

### ISSUE THREAD

**Issue by fniephaus** [dalehenrich/builderCI#101]
There's something wrong with the current `Pharo-5.0` build:
https://travis-ci.org/dalehenrich/builderCI/jobs/72311615#L412

Maybe @demarey can help?

**Comment by demarey** [comment]
We updated metacelloPlatformAttributes in Pharo 5 from ```#(#squeakCommon #pharo #'pharo4.x' #'pharo4.0.x' #'pharo5.x' #'pharo5.0.x')``` to ```#(#squeakCommon #pharo #'pharo5.x' #'pharo5.0.x')```. It means that metacello may now fallback to load an inappropriate version if no instruction is given for Pharo 5.
I think builderCI tests try to update filetree/metacello, right?

**Comment by demarey** [comment]
The problem comes from [scripts/bootstrapMetacello.st](https://github.com/dalehenrich/builderCI/blob/master/scripts/bootstrapMetacello.st#L52). Even if present, Metacello is reloaded. And Metacello will not work if it is not updated to use the pharo5.0 branch of FileTree for pharo 5.0.
There is a pending pull request for that: https://github.com/dalehenrich/metacello-work/pull/351.
It is the chicken and egg syndrome: the tests of the pull requests fail because travisCI do not use the up-to-date metacallo version provided by the pull request ...
@dalehenrich I think you can safely include the pull request and it will solve problems. I have tests green on Jenkins

**Comment by dalehenrich** [comment]
I will start looking into this today ...

**Comment by dalehenrich** [comment]
merged https://github.com/dalehenrich/metacello-work/pull/351

**Comment by dalehenrich** [comment]
this is fixed methinks
