### ISSUE TITLE
Use GitHub releases

### ISSUE THREAD

**Issue by fniephaus** [dalehenrich/builderCI#88]
Hi @dalehenrich,

Currently, most people simply use the master branch in their `.travis.yml` which is great, because they always get the latest builderCI. But as we saw, changes like #85 can cause unwanted problems for these users.

How about you tag stable releases after some testing and turn them into GitHub releases?

We should be able to replace ```https://github.com/dalehenrich/builderCI/zipball/master``` with a link to the latest release, so that users will always get the latest *stable* builderCI.

Besides, if builderCI has more tags/releases, people can also use them instead in case they don't want/need updates.

Let me know what you think. I'd be happy to help you with this.

Regards,
Fabio

**Comment by dalehenrich** [comment]
@fniephaus, that's not a bad idea ... all of my usage will stay with the master branch, but giving folks the option of locking in a tag is a good thing

**Comment by dalehenrich** [comment]
@fniephaus I'm inclined to tag the current master as v1.0.0, unless you have a different idea ...

**Comment by fniephaus** [comment]
Sounds reasonable. And we eventually need to start with v1.0.0 :)

**Comment by fniephaus** [comment]
I just thought about it once more and it might be easier to also use a `stable` tag that we always move to the latest stable release.

So this all would look like this:
- Latest (unstable): https://github.com/dalehenrich/builderCI/archive/master.zip
- Latest (stable): https://github.com/dalehenrich/builderCI/archive/stable.zip
- Specific version: https://github.com/dalehenrich/builderCI/archive/v0.9.0.zip

Unfortunately, GitHub does not seem to provide a direct way to *download* the latest release. All solutions to this problem require at least one more (API) request.

What do you think?

**Comment by dalehenrich** [comment]
Yeah, I don't like using stable like this ... of course if you find it really useful, then I wouldn't say *no*, I'd just say that *I don't use it* ... Basically by definition the latest version on the master branch is the "latest stable". I don't push anything to the master branch that does not pass the unit tests, so in essence there is no difference between *master* and *stable*.

There is value in using tags for [semantic versioning](http://semver.org/) style api management ... with the major, minor and patch version numbers. patch version is incremented on bugfixes, minor version is incremented on backwards compatible api changes and major version is incremented on non-backwards compatible api changes ...

I added [tag pattern matching](https://github.com/dalehenrich/metacello-work/issues/277#issuecomment-58970696) to Metacello so that one could say that they wanted to use 1.0.? or 1.? or master ... which combines the best of both worlds ... the master branch is a rolling stable release that passes all tests. tagged versions are checkpoints along the master branch (usually) where documentation is written or the set of bugfixes/api changes is large enough to warrant announcing something

**Comment by fniephaus** [comment]
I see your point. And you're right, it's just too much overhead to maintain a stable tag/branch since the master should *already* be stable.
Besides, I agree ... semantic versioning is definitely the way to go here.
So let's stick to your suggestion then :smiley:

**Comment by dalehenrich** [comment]
I see you deleted your v0.9.0 tag ... now is as good a time as any to start with v1.0.0:)

**Comment by fniephaus** [comment]
Yes, I just wanted to try something out but now I've tagged 8d7e6a255c7d00c7c0079182b6ccfc1e555f2ca7 as `v1.0.0`.
I hope you don't mind that I also cleaned up the legacy tags since they are [still available](https://github.com/renggli/builder/releases) in the original repository.

**Comment by dalehenrich** [comment]
Looks good! Love it!

**Comment by fniephaus** [comment]
:smile:
